
[broadcast]
	debugEnabled = false
	triggerPrefix = "#全体 "
	#Range: 0.0 ~ 1.0
	baseChance = 0.4
	#Range: 1 ~ 64
	searchRadius = 16
	#Range: 0.0 ~ 1.0
	nameMentionBonus = 0.5
	#Range: 1 ~ 20
	maxResponders = 5
	#Range: 0 ~ 300
	apiCallsPerMinute = 20
	ownerDamageBypassEnabled = true
	#Allowed Values: NONE, BASIC, ULTIMATE
	ownerDamageProtectionBreakLevel = "ULTIMATE"

[talk_event]
	enabled = true
	#Range: 2 ~ 10
	minMaids = 5
	#Range: 1 ~ 20
	replyIntervalSeconds = 1

[npc_event]
	enableNpcEventAiReply = true

[betrayal]
	betrayalMaidExplosionBreakBlocks = true

