
[emotion_passive]
	sitDetectionEnabled = false
	#Range: -10 ~ 10
	sitTrustChange = -2
	#Range: -10 ~ 10
	sitFearChange = -2

[wandering_maid]
	#Range: 0 ~ 60
	spawnIntervalMinutes = 5
	#Range: 1 ~ 10
	maidsPerPlayer = 1
	dropBlacklist = []
	dropWhitelist = []
	#Range: 0 ~ 100
	spawnChancePercent = 25

[wandering_trader_maid_trade]
	enabled = true

[doting_possessive]
	#Range: 0 ~ 10
	intervalMinutes = 1
	#Range: 10 ~ 120
	durationSeconds = 20

